### ISSUE TITLE
Change tags / list tags

### ISSUE THREAD

**Issue by togglebyte** [togglebyte/twitchctl#2]
Change tags: https://dev.twitch.tv/docs/api/reference#replace-stream-tags
Get current tags for stream: https://dev.twitch.tv/docs/api/reference#get-stream-tags
Get all tags: https://dev.twitch.tv/docs/api/reference#get-all-stream-tags

**Comment by togglebyte** [comment]
```
twitchctl tags listall   <- list all tags
twitchctl tags list   <- list all tags
twitchctl tags set [<tag_id>]
twitchctl tags add [<tag_id>]
```

`add <tag_id>` pulls current tags and appends the new ones.
`set [<tag_id>]` replaces all existing tags with the new list.

**Comment by ModProg** [comment]
Working on the PullRequest for twitch_api2 https://github.com/Emilgardis/twitch_api2/pull/89

**Comment by ModProg** [comment]
Merged, The Library should now be able to do everything we need.
